### ISSUE TITLE
custom maps arent working

### ISSUE THREAD

**Issue by sidasltu** [PhantomYopta/LiteMapChooser#9]
cs_italy
cs_office
de_dust2
de_inferno
de_mirage
de_nuke
de_overpass
de_vertigo
ws:awp_india
ws:awp_lego_2_winter
ws:1v1aim_map_longdustversion_d
ws:aim_ancient
ws:fy_pool_day
ws:de_biome
ws:awp_lego_cs2
ws:aim_deagle
ws:aim_shaft
ws:aim_inferno_warmup
ws:fy_snow_y0
ws:aim_crashz_dust_1on1
there is ws example if i start server on de_biome when write rtv and select biome its change but if i select othet example aim_deagle is not working

**Comment by DrOetcker** [comment]
Also have this issue. Seems to be have something to do with the name of the maps. even when you try to change the map via rcon thy do not work

**Comment by Nubezzi** [comment]
@DrOetcker @sidasltu I have been able to use workshop maps. In my server launch command, I include "host_workshop_collection [id]" and i have published a collection of ws maps to workshop. This loads these maps to the server and I can see that these have been loaded successfully with "ds_workshop_listmaps" then i can change maps with "ds_workshop_changelevel de_somemap" or with the rtv command

**Comment by DrOetcker** [comment]
@Nubezzi You are basically right. The maps indeed are loading corretly, but what I (in my case) wanted to point out, that for example maps like "aim_deagle (usp)" are not able to load.
I guess, this is the case because the map (at least as far as I know, please correct me if Im wrong!) is loaded by the source_folder rather its name.
Here is the screnario: Add "aim_deagle" and "aim_deagle (usp)" to your collection and try to load "aim_deagle (usp)".
For me non of the ways to load a map is working for "aim_deagle (usp)" (ds_wor....., rtv, fake_rcon).
Maybe I was a little blind for @sidasltu's problem because of the map he was trying to load 🙈

**Comment by Letaryat** [comment]
Does anyone have any idea why maps doesn't change after !rtv and voted has ended? It doesn't change to any map (either workshop or default cs2 map)
Using CSS 110. The only console log that it could be related with the plugin might be:
`CSSharp: Native a5901a5e was invoked on a non-main thread`

**Comment by Nubezzi** [comment]
@Letaryat CSS doesnt like async execution in some cases and requires code to run in the main thread. You can try to restart the plugin with css_plugins restart RockTheVote. If the plugin restarts with no issues, i think the issue is not in the plugin.
Have you tried to change the map with commands straight from the server console with 'changelevel de_map' or 'ds_workshop_changelevel de_wsmap' ?

**Comment by Letaryat** [comment]
@Nubezzi Changing the map using "ds_workshop_changelevel" does work but "changelevel", "map" doesnt. Restarting plugin, server and reinstalling plugin nothing work. I dunno if I did something wrong. I have maplist.txt and mapcycle.txt files (even tried without them). Tried even 112 CSS version and still the same. Map doesn't change, only information on chat is printed that map has won by voting and then nothing happens. 
Plugin restarts just fine.

Thanks for responding.

Edit:
Plugin works just fine on older version of CSS but not on the newest (115). I think it needs to be updated.

**Comment by Ryuujin555** [comment]
@Letaryat Well i used also older CSS and it work for normal maps but not for workshop ones at least for me, or i am missing out something ?

**Comment by Letaryat** [comment]
@Ryuujin555 
In maps.txt files you should put maps like this:
ws:surf_kitsune
ws:surf_mesa
etc.

Well I stopped using this plugin because it's outdated and I needed a newest version of CSS and I'm using different solution now.

**Comment by Ryuujin555** [comment]
@Letaryat Tried it that way but it aint loading a thing :( używasz jakiegoś innego nowsze pluginu do ogarniania takich zmian mapek mój dc : ryuujin5066
